[package]
name = "terminusrust"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = { version = "0.30", features = ["x11", "egl"] }
winit = "0.30"
nix = "0.26"
lazy_static = "1.4"
raw-window-handle = "0.5"

